apiVersion: v1
kind: ServiceMonitor
metadata:
  name: liquid-metal-antenna-monitor
  labels:
    app: liquid-metal-antenna-optimizer
    release: prometheus
spec:
  selector:
    matchLabels:
      app: liquid-metal-antenna-optimizer
  endpoints:
  - port: http
    path: /metrics
    interval: 30s
    scrapeTimeout: 10s

---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: liquid-metal-antenna-alerts
  labels:
    app: liquid-metal-antenna-optimizer
    prometheus: kube-prometheus
    role: alert-rules
spec:
  groups:
  - name: liquid-metal-antenna.rules
    rules:
    - alert: LiquidMetalAntennaHighErrorRate
      expr: rate(http_requests_total{job="liquid-metal-antenna-optimizer",code=~"5.."}[5m]) / rate(http_requests_total{job="liquid-metal-antenna-optimizer"}[5m]) > 0.1
      for: 5m
      labels:
        severity: warning
      annotations:
        summary: High error rate detected
        description: "Error rate is {{ $value | humanizePercentage }} for {{ $labels.instance }}"

    - alert: LiquidMetalAntennaHighLatency
      expr: histogram_quantile(0.95, rate(http_request_duration_seconds_bucket{job="liquid-metal-antenna-optimizer"}[5m])) > 5
      for: 10m
      labels:
        severity: warning
      annotations:
        summary: High request latency
        description: "95th percentile latency is {{ $value }}s for {{ $labels.instance }}"

    - alert: LiquidMetalAntennaOptimizationBacklog
      expr: active_optimizations{job="liquid-metal-antenna-optimizer"} > 100
      for: 15m
      labels:
        severity: critical
      annotations:
        summary: High optimization backlog
        description: "{{ $value }} active optimizations on {{ $labels.instance }}"

    - alert: LiquidMetalAntennaWorkerDown
      expr: up{job="liquid-metal-antenna-optimizer"} == 0
      for: 1m
      labels:
        severity: critical
      annotations:
        summary: Liquid Metal Antenna optimizer is down
        description: "{{ $labels.instance }} has been down for more than 1 minute"

    - alert: LiquidMetalAntennaHighMemoryUsage
      expr: (container_memory_working_set_bytes{pod=~"liquid-metal-antenna-optimizer-.*"} / container_spec_memory_limit_bytes) > 0.9
      for: 10m
      labels:
        severity: warning
      annotations:
        summary: High memory usage
        description: "Memory usage is {{ $value | humanizePercentage }} on {{ $labels.pod }}"

    - alert: LiquidMetalAntennaHighCPUUsage
      expr: rate(container_cpu_usage_seconds_total{pod=~"liquid-metal-antenna-optimizer-.*"}[5m]) / container_spec_cpu_quota * 100 > 90
      for: 15m
      labels:
        severity: warning
      annotations:
        summary: High CPU usage
        description: "CPU usage is {{ $value }}% on {{ $labels.pod }}"

    - alert: LiquidMetalAntennaOptimizationFailureRate
      expr: rate(optimizations_total{job="liquid-metal-antenna-optimizer",status="failed"}[10m]) / rate(optimizations_total{job="liquid-metal-antenna-optimizer"}[10m]) > 0.2
      for: 5m
      labels:
        severity: critical
      annotations:
        summary: High optimization failure rate
        description: "{{ $value | humanizePercentage }} of optimizations are failing on {{ $labels.instance }}"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-dashboard-liquid-metal-antenna
  labels:
    grafana_dashboard: "1"
data:
  liquid-metal-antenna-dashboard.json: |
    {
      "dashboard": {
        "id": null,
        "title": "Liquid Metal Antenna Optimizer",
        "tags": ["optimization", "antenna", "liquid-metal"],
        "style": "dark",
        "timezone": "browser",
        "panels": [
          {
            "id": 1,
            "title": "Request Rate",
            "type": "graph",
            "targets": [
              {
                "expr": "rate(http_requests_total{job=\"liquid-metal-antenna-optimizer\"}[5m])",
                "legendFormat": "{{ method }} {{ endpoint }}"
              }
            ],
            "yAxes": [
              {
                "label": "Requests/sec",
                "min": 0
              }
            ],
            "gridPos": {"h": 8, "w": 12, "x": 0, "y": 0}
          },
          {
            "id": 2,
            "title": "Response Time",
            "type": "graph",
            "targets": [
              {
                "expr": "histogram_quantile(0.95, rate(http_request_duration_seconds_bucket{job=\"liquid-metal-antenna-optimizer\"}[5m]))",
                "legendFormat": "95th percentile"
              },
              {
                "expr": "histogram_quantile(0.50, rate(http_request_duration_seconds_bucket{job=\"liquid-metal-antenna-optimizer\"}[5m]))",
                "legendFormat": "50th percentile"
              }
            ],
            "yAxes": [
              {
                "label": "Seconds",
                "min": 0
              }
            ],
            "gridPos": {"h": 8, "w": 12, "x": 12, "y": 0}
          },
          {
            "id": 3,
            "title": "Active Optimizations",
            "type": "stat",
            "targets": [
              {
                "expr": "active_optimizations{job=\"liquid-metal-antenna-optimizer\"}",
                "legendFormat": "Active Jobs"
              }
            ],
            "gridPos": {"h": 4, "w": 6, "x": 0, "y": 8}
          },
          {
            "id": 4,
            "title": "Optimization Success Rate",
            "type": "stat",
            "targets": [
              {
                "expr": "rate(optimizations_total{job=\"liquid-metal-antenna-optimizer\",status=\"completed\"}[10m]) / rate(optimizations_total{job=\"liquid-metal-antenna-optimizer\"}[10m])",
                "legendFormat": "Success Rate"
              }
            ],
            "gridPos": {"h": 4, "w": 6, "x": 6, "y": 8}
          },
          {
            "id": 5,
            "title": "Memory Usage",
            "type": "graph",
            "targets": [
              {
                "expr": "container_memory_working_set_bytes{pod=~\"liquid-metal-antenna-optimizer-.*\"} / 1024 / 1024 / 1024",
                "legendFormat": "{{ pod }}"
              }
            ],
            "yAxes": [
              {
                "label": "GB",
                "min": 0
              }
            ],
            "gridPos": {"h": 8, "w": 12, "x": 12, "y": 8}
          },
          {
            "id": 6,
            "title": "CPU Usage",
            "type": "graph",
            "targets": [
              {
                "expr": "rate(container_cpu_usage_seconds_total{pod=~\"liquid-metal-antenna-optimizer-.*\"}[5m]) * 100",
                "legendFormat": "{{ pod }}"
              }
            ],
            "yAxes": [
              {
                "label": "CPU %",
                "min": 0,
                "max": 100
              }
            ],
            "gridPos": {"h": 8, "w": 12, "x": 0, "y": 16}
          },
          {
            "id": 7,
            "title": "Optimization Types",
            "type": "piechart",
            "targets": [
              {
                "expr": "sum by (type) (rate(optimizations_total{job=\"liquid-metal-antenna-optimizer\"}[10m]))",
                "legendFormat": "{{ type }}"
              }
            ],
            "gridPos": {"h": 8, "w": 12, "x": 12, "y": 16}
          },
          {
            "id": 8,
            "title": "Regional Distribution",
            "type": "table",
            "targets": [
              {
                "expr": "count by (region) (up{job=\"liquid-metal-antenna-optimizer\"})",
                "legendFormat": "Workers",
                "format": "table"
              }
            ],
            "gridPos": {"h": 6, "w": 24, "x": 0, "y": 24}
          }
        ],
        "time": {
          "from": "now-1h",
          "to": "now"
        },
        "refresh": "30s"
      }
    }

---
apiVersion: logging.coreos.com/v1
kind: ClusterLogForwarder
metadata:
  name: liquid-metal-antenna-logs
  namespace: openshift-logging
spec:
  outputs:
  - name: elasticsearch-optimizer
    type: "elasticsearch"
    url: "https://elasticsearch.liquid-metal-antenna.com:9200"
    secret:
      name: elasticsearch-credentials
  pipelines:
  - name: optimizer-logs
    inputRefs:
    - application
    filterRefs:
    - optimizer-filter
    outputRefs:
    - elasticsearch-optimizer

---
apiVersion: logging.coreos.com/v1
kind: ClusterLogForwarder
metadata:
  name: optimizer-filter
  namespace: openshift-logging
spec:
  filters:
  - name: optimizer-filter
    type: json
    json:
      javascript: |
        const log = record.log;
        if (log && log.includes('liquid-metal-antenna-optimizer')) {
          record.optimizer_service = true;
          
          // Extract optimization metrics
          if (log.includes('optimization_job')) {
            const match = log.match(/job_id:(\w+)/);
            if (match) {
              record.job_id = match[1];
            }
          }
          
          // Extract performance metrics
          if (log.includes('duration:')) {
            const match = log.match(/duration:([\d.]+)s/);
            if (match) {
              record.optimization_duration = parseFloat(match[1]);
            }
          }
        }
        return record;